### PR TITLE
Changing today's bonuses so it grabs from the beginning of the day

### PR DESCRIPTION
**Pull request by robertIngrum**

### CODE REVIEW

**Comment by robertIngrum** [comment]
Self approve because I need it in order to bundle install the new version 🐙

**Comment by raphaelcm** [comment]
Does this change do something sensible for companies with offices that span different timezones?

**Comment by robertIngrum** [comment]
Not until I merge in the pr on special sauce [here](https://github.com/bonusly/special_sauce/pull/5521).  It'll change the duration so that it shows today's bonuses from the beginning of the company's timezone's day instead of a raw 24 hours.

**Comment by robertIngrum** [comment]
Which now that I think about it might make more sense just to grab the local computer's time since the beginning of the day...

**Comment by raphaelcm** [comment]
For our largest customers, there isn't a single Company time zone. They almost all have offices in many different time zones.

**Pull request merged**
